### ISSUE TITLE
Admin | Sync Template v2 (Power Apps User Shared With) Error 

### ISSUE THREAD

**Issue by aakashpatel660** [microsoft/powerapps-tools#397]
**Describe the bug**
I am getting error for invalid type for entity id value at Insert Power Platform User action. 

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution - Core
 - Version - 1.54
 - Flow - Admin | Sync Template v2 (Power Apps User Shared With)

**To Reproduce**
1. Go to 

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/59940632/88716543-35ffbb00-d0ed-11ea-8623-fe065b30a853.png)

![image](https://user-images.githubusercontent.com/59940632/88716586-42841380-d0ed-11ea-885b-608686f4dd9d.png)

**Additional context**
{
  "error": {
    "code": "0x80040203",
    "message": "Invalid type for entity id value",
    "innererror": {
      "message": "Invalid type for entity id value",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.CreateInternal(Entity entity, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.CreateOrganizationResponse(Entity entity)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.CreateEdmEntity(CrmODataExecutionContext context, String edmEntityName, EdmEntityObject entityObject, Boolean isUpsert)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PostEntitySetImplementation(String& entitySetName, EdmEntityObject entityObject)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    },
    "@Microsoft.PowerApps.CDS.ErrorDetails.ValidationPath": "/0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Api/PrePipeline",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "00000000-0000-0000-0000-000000000000",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "509ffc31-8ffd-4681-b623-8bade033c170",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "InvalidArgument",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "400",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040203&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Invalid type for entity id value"
  }
}

**Comment by JeneferM-MSFT** [comment]
It looks like you have the wrong parameters to that call somehow. The inputs to it should look like this:
![image](https://user-images.githubusercontent.com/62659043/88721519-6dfe0280-d0db-11ea-88f3-56934aaa8229.png).

Can you please re-import the core solution? Be sure to chose overwrite customizations when prompted, it is not the default. 
See near the bottom of #394  for what this ux looks like

**Comment by aakashpatel660** [comment]
Hello 

For version 1.54 I did overwrite customization but I will try 1 more time. And let you know. 

Best Regards,
Akash Patel

**Comment by aakashpatel660** [comment]
Hello

I did overwrite customization for core solution 1.54 and having the same issue still. Here is the error message I am receiving. 

![image](https://user-images.githubusercontent.com/59940632/88814674-706a6600-d188-11ea-8505-ea8c95205b55.png)

![image](https://user-images.githubusercontent.com/59940632/88814719-7bbd9180-d188-11ea-92da-6e69608d279d.png)


{
  "error": {
    "code": "0x80040203",
    "message": "Invalid type for entity id value",
    "innererror": {
      "message": "Invalid type for entity id value",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.CreateInternal(Entity entity, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.CreateOrganizationResponse(Entity entity)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.CreateEdmEntity(CrmODataExecutionContext context, String edmEntityName, EdmEntityObject entityObject, Boolean isUpsert)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PostEntitySetImplementation(String& entitySetName, EdmEntityObject entityObject)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    },
    "@Microsoft.PowerApps.CDS.ErrorDetails.ValidationPath": "/0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Api/PrePipeline",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "00000000-0000-0000-0000-000000000000",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "ae81fab8-e2e5-4ef6-9434-e53bf6a54b49",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "InvalidArgument",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "400",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040203&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Invalid type for entity id value"
  }
}

**Comment by JeneferM-MSFT** [comment]
Yes, if you wish to get updates from us on the toolkit, you need to overwrite changes in your flow with every upgrade.

Somehow you have the wrong parameters going in to the flow. Can you please show me what the flow looks like in edit mode? Here is what those two calls are supposed to look like. Perhaps you accidently deleted the item id,
![image](https://user-images.githubusercontent.com/62659043/89917068-9bf04600-dbb5-11ea-9d7b-60a81843e993.png)
![image](https://user-images.githubusercontent.com/62659043/89917108-a7dc0800-dbb5-11ea-99ff-d80179680717.png)

**Comment by JeneferM-MSFT** [comment]
Can you also please share with me:
For this failure:
1) The outcome of this call: Get App Role Assignments as Admin
1) If this is failing for all items in the loop or just some: Apply to Each
1) For a failing record, what the value for this variable is from the switch statement above:  sharedGroupSize

For the runs generally:
This gets called multiple times in a row for the apps. Does this fail for many apps or just some? 
If just some apps, can you see if those apps are in a good state?

**Comment by aakashpatel660** [comment]
Here are the picture with edit mode. 
![image](https://user-images.githubusercontent.com/59940632/90023684-ffe04080-dc81-11ea-8bbb-7c9a49783835.png)

![image](https://user-images.githubusercontent.com/59940632/90023737-138ba700-dc82-11ea-8207-d512e9bfd486.png)

Here is the picture for the Get App Role Assignments as admin 
![image](https://user-images.githubusercontent.com/59940632/90024471-e390d380-dc82-11ea-8576-c4d7f876b23f.png)

Outcome of the Get App Role Assignments as admin
{
    "name": "35b0aa6b-556d-4503-b42c-d22b78762416",
    "id": "/providers/Microsoft.PowerApps/scopes/admin/apps/b31b7fa0-8ac3-4bde-a6c3-413a1b3d3c6e/permissions/35b0aa6b-556d-4503-b42c-d22b78762416",
    "type": "Microsoft.PowerApps/scopes/apps/permissions",
    "properties": {
      "roleName": "Owner",
      "principal": {
        "id": "35b0aa6b-556d-4503-b42c-d22b78762416",
        "displayName": "",
        "email": "",
        "type": "User",
        "tenantId": ""
      },
      "scope": "/providers/Microsoft.PowerApps/environments/Default-68a7ff20-812f-4738-90ea-0b1051846f74/apps/b31b7fa0-8ac3-4bde-a6c3-413a1b3d3c6e",
      "notifyShareTargetOption": "NotSpecified",
      "inviteGuestToTenant": false
    }
  },
  {
    "name": "tenant-68a7ff20-812f-4738-90ea-0b1051846f74",
    "id": "/providers/Microsoft.PowerApps/apps/b31b7fa0-8ac3-4bde-a6c3-413a1b3d3c6e/permissions/tenant-68a7ff20-812f-4738-90ea-0b1051846f74",
    "type": "Microsoft.PowerApps/apps/permissions",
    "properties": {
      "roleName": "CanView",
      "principal": {
        "type": "Tenant",
        "tenantId": "68a7ff20-812f-4738-90ea-0b1051846f74"
      },
      "scope": "/providers/Microsoft.PowerApps/environments/Default-68a7ff20-812f-4738-90ea-0b1051846f74/apps/b31b7fa0-8ac3-4bde-a6c3-413a1b3d3c6e",
      "notifyShareTargetOption": "NotSpecified",
      "inviteGuestToTenant": false
    }
  }
]

Flow runs multiple times and it fails for some of the runs, not all some are getting successful runs and some are failing. Apply to each has only 2 loops. 

![image](https://user-images.githubusercontent.com/59940632/90025274-e50ecb80-dc83-11ea-9e20-5b9c35791321.png)

**Comment by JeneferM-MSFT** [comment]
Thanks for sharing that great information, it helped me find what I believed to be the cause and a fix. 
Can you please test with the attached flow? Note that its a flow and not a solution so you will need to import via [flow.microsoft.com](https://flow.microsoft.com)

[PowerAppsUserShareWithFix_20200814152339.zip](https://github.com/microsoft/powerapps-tools/files/5075419/PowerAppsUserShareWithFix_20200814152339.zip)

**Comment by JeneferM-MSFT** [comment]
We have released this fix. 
Thanks for using CoE!

**Comment by aakashpatel660** [comment]
Hello

Still having the issue. I did try the flow which you gave me and imported that and here is the error message. 

![image](https://user-images.githubusercontent.com/59940632/90449711-fc9be900-e0b5-11ea-9150-b1735590c81b.png)

![image](https://user-images.githubusercontent.com/59940632/90449725-058cba80-e0b6-11ea-945d-a8b24c0a55bb.png)

Error Message - 
{
  "error": {
    "code": "0x80040203",
    "message": "Invalid type for entity id value",
    "innererror": {
      "message": "Invalid type for entity id value",
      "type": "System.ServiceModel.FaultException`1[[Microsoft.Xrm.Sdk.OrganizationServiceFault, Microsoft.Xrm.Sdk, Version=9.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]",
      "stacktrace": "   at Microsoft.Crm.Extensibility.OrganizationSdkServiceInternal.CreateInternal(Entity entity, InvocationContext invocationContext, CallerOriginToken callerOriginToken, WebServiceType serviceType, Boolean checkAdminMode, Dictionary`2 optionalParameters)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataExecutionContext.CreateOrganizationResponse(Entity entity)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataServiceDataProvider.CreateEdmEntity(CrmODataExecutionContext context, String edmEntityName, EdmEntityObject entityObject, Boolean isUpsert)\r\n   at Microsoft.Crm.Extensibility.OData.EntityController.PostEntitySetImplementation(String& entitySetName, EdmEntityObject entityObject)\r\n   at Microsoft.Crm.Extensibility.OData.CrmODataUtilities.<>c__DisplayClass10_0`2.<InvokeActionAndLogMetric>b__0()\r\n   at Microsoft.PowerApps.CoreFramework.ActivityLoggerExtensions.Execute[TResult](ILogger logger, EventId eventId, ActivityType activityType, Func`1 func, IEnumerable`1 additionalCustomProperties)\r\n   at Microsoft.Xrm.Telemetry.XrmTelemetryExtensions.Execute[TResult](ILogger logger, XrmTelemetryActivityType activityType, Func`1 func)\r\n   at lambda_method(Closure , Object , Object[] )\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)\r\n   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
    },
    "@Microsoft.PowerApps.CDS.ErrorDetails.ValidationPath": "/0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionSourceKey": "Api/PrePipeline",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepKey": "00000000-0000-0000-0000-000000000000",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiDepthKey": "0",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiActivityIdKey": "707df179-5334-4d52-8bb8-61675cdded69",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiPluginSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiStepSolutionNameKey": "System",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionCategory": "ClientError",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionMesageName": "InvalidArgument",
    "@Microsoft.PowerApps.CDS.ErrorDetails.ApiExceptionHttpStatusCode": "400",
    "@Microsoft.PowerApps.CDS.HelpLink": "http://go.microsoft.com/fwlink/?LinkID=398563&error=Microsoft.Crm.CrmException%3a80040203&client=platform",
    "@Microsoft.PowerApps.CDS.InnerError.Message": "Invalid type for entity id value"
  }
}


Below error is after installing new version which was released today. 

![image](https://user-images.githubusercontent.com/59940632/90449918-6b794200-e0b6-11ea-825a-f1ce3b5e9747.png)

{
  "error": {
    "code": "ApplicationNotFound",
    "message": "The application '25bd503c-c8cc-4f87-b069-fdca8004532c' could not be found in the tenant '68a7ff20-812f-4738-90ea-0b1051846f74'."
  }
}

**Comment by JeneferM-MSFT** [comment]
Did you try the flow that was released yesterday to the GitHub repository? It had an additional change from a colleague.

Here is just that flow from the download:

[AdminSyncTemplatev2(PowerAppsUserSharedWith)_20200817233107.zip](https://github.com/microsoft/powerapps-tools/files/5087290/AdminSyncTemplatev2.PowerAppsUserSharedWith._20200817233107.zip)

**Comment by aakashpatel660** [comment]
Thank you so much for your all help and thank you for the CoE Kit. Issue has been resolved.
