### ISSUE TITLE
[BUG]: Admin|Sync Template v2 (Custom Connectors) & (Flows)

### ISSUE THREAD

**Issue by ofuen** [microsoft/powerapps-tools#424]
**Describe the bug**
1. Is not finding the connections. 
2. When i select "Save As" to make a copy. I get the following error. for Both - Admin|Sync Template v2 (Custom Connectors) & (Flows).
"The pagination policy of workflow run action 'Find_connector_record' of type 'ApiConnection' at line '1' and column '6206' is not valid. The value specified for property 'minimumItemsCount' exceeds the maximum allowed. Actual: '10000'. Maximum: '5000'."

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution [Center Of Excellence - Core Components]
 - Version [1.60]
 - Flow [Admin|Sync Template v2 (Custom Connectors) & (Flows) ]

**To Reproduce**
1. Go to 'Solutions'
2. Click on 'Center Of Excellence - Core Components'
3. Scroll down to 'Admin|Sync Template v2 (Custom Connectors) & (Flows)

**Expected behavior**
To save a copy of the Flow.

**Screenshots**
![image](https://user-images.githubusercontent.com/19554935/90251075-2a113a00-de0b-11ea-82fa-32f438e19c3d.png)
![image](https://user-images.githubusercontent.com/19554935/90252031-cee04700-de0c-11ea-8644-2bd55118a9b0.png)
![image](https://user-images.githubusercontent.com/19554935/90251245-6775c780-de0b-11ea-8ced-b3c4f2b0fb66.png)
![image](https://user-images.githubusercontent.com/19554935/90251374-9855fc80-de0b-11ea-9ed0-dcd363e54f1f.png)
![image](https://user-images.githubusercontent.com/19554935/90251396-a6a41880-de0b-11ea-81e9-1bdc69630720.png)

**Additional context**
Let me know if you need any additional information.  l 'am the admin access and also have a "Power Apps per user plan"

**Comment by JeneferM-MSFT** [comment]
Hello. These have been fixed in the new version of Core. I validated the one you showed is fixed, if you find a case we missed in flow, after you upgrade, please let us know.

Be sure to hit overwrite when you do the upgrade.
![image](https://user-images.githubusercontent.com/62659043/90257659-507ba900-ddfc-11ea-913b-442d19375d5d.png)
 
Thanks for using CoE

**Comment by ofuen** [comment]
Thank you @JeneferM-MSFT , Let me give it a try and circle back.

**Comment by ofuen** [comment]
Hi @JeneferM-MSFT, So  after Upgrading and Overwriting it, "Admin|Sync Template v2 (Flows)" is fixed was able to (Save as) Copy.  Still getting the same error for - "Admin|Sync Template v2 (Custom Connectors)"
![image](https://user-images.githubusercontent.com/19554935/90262363-3a7de080-de1c-11ea-817d-b7fc0466cd8f.png)

- When i try to edit the flow.
![image](https://user-images.githubusercontent.com/19554935/90262464-571a1880-de1c-11ea-9550-6c32cf4b9215.png)

1.  I add Existing connection
![image](https://user-images.githubusercontent.com/19554935/90262544-6e590600-de1c-11ea-9845-fffe1f74d8ca.png)
![image](https://user-images.githubusercontent.com/19554935/90262654-9183b580-de1c-11ea-971d-ad9f9399481a.png)

2. The same for the second
![image](https://user-images.githubusercontent.com/19554935/90262763-b2e4a180-de1c-11ea-8c66-384958d19e1c.png)
![image](https://user-images.githubusercontent.com/19554935/90262904-eb847b00-de1c-11ea-8506-0aafb9030fb8.png)

Let me know if i should just create a new environment and install the new version?

**Comment by JeneferM-MSFT** [comment]
ok we found one we missed. If you change the pagination on this one to 5000, you should be ok. 
Change pagination by hitting the <...> then settings, and change pagination threashold to 5000

![image](https://user-images.githubusercontent.com/62659043/90266361-b53d0080-de08-11ea-91ca-a5535733fdfe.png)

**Comment by ofuen** [comment]
We are almost there, change pagination Threshold to 5000
Now getting this.
![image](https://user-images.githubusercontent.com/19554935/90270851-ddd4f280-de28-11ea-93c5-a5e6b48f12cf.png)

Thank you for help @JeneferM-MSFT

**Comment by JeneferM-MSFT** [comment]
hmmm not sure how that got cleared out for you, but here is the entity to select

![image](https://user-images.githubusercontent.com/62659043/90272361-2339f580-de12-11ea-9469-e17514299a90.png)

**Comment by ofuen** [comment]
Issue has been fixed :) You could closed the ticket.

**Comment by JeneferM-MSFT** [comment]
wonderful. Thanks for using CoE!
