### ISSUE TITLE
[BUG]: Admin | Sync Template v2 (PVA) | Action 'Get_this_Bot_from_CoE' failed

### ISSUE THREAD

**Issue by albertocaa1317** [microsoft/powerapps-tools#580]
The flow  "Admin | Sync Template v2 (PVA)" fails with the error in the attached screenshots.

Can you help me to solve this?
Thanks!

**Component (please tell us which flow or app you are experiencing issues with):**
 - Solution: Core
 - Version: 1.71
 - App or Flow: Admin | Sync Template v2 (PVA)

![image](https://user-images.githubusercontent.com/57954993/99507109-416c4000-2983-11eb-86bc-06109a488875.png)

Body message:
{
  "status": 404,
  "message": "admin_pva With Id = 4c080563-2ed9-4268-8063-27935a032a46 Does Not Exist",
  "error": {
    "message": "admin_pva With Id = 4c080563-2ed9-4268-8063-27935a032a46 Does Not Exist"
  },
  "source": "org58a90771.crm4.dynamics.com",
  "errors": [],
  "debugInfo": "clientRequestId: d05b37b6-12b0-406f-b7cf-ee07ce9004b7"
}

**Comment by mpinuel** [comment]
Same issue on my part. Yesterday I installed last Core Components version 1.71.1 and I've the same error reported on Admin | Sync Template v2 (PVA) in action 'Get_this_Bot_from_CoE': 
**admin_pva With Id = XXXX Does Not Exist**

Thanks!

**Comment by JeneferM-MSFT** [comment]
Thank you for posting and helping make CoE great! I have found the bug thanks to your help.
We were checking too many things in a single if clause. I have local fixed this for next release.

If you would like to fix this locally while you await release, note that you will need to **remove the unmanaged layer** that is generated before you upgrade next time, or you will not receive the update. 

For more information when ready for next upgrade, please see [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

The fix:
In the "See if Modified" Scope, you will need to create a second condition, to make the check for new and check for modified separate, as shown here:
![image](https://user-images.githubusercontent.com/62659043/99568751-9ceafd80-2984-11eb-95cd-9d52f027ff04.png)

**Comment by JeneferM-MSFT** [comment]
This has been resolved in the new version of the toolkit released today: [https://aka.ms/CoEStarterKitDownload](https://aka.ms/CoEStarterKitDownload)

**PLEASE NOTE:** In order to receive updates, you now have to remove all unmanaged layers from any apps/flows you have created in the past. Otherwise you will not see the changes for the app/flow that maintains its unmanaged layers. 

For more details on what this looks like, please view [installing updates](https://docs.microsoft.com/power-platform/guidance/coe/setup#installing-updates)

Thanks for using CoE, and helping make it great with your feedback.

**Comment by JeneferM-MSFT** [comment]
Somehow our fix did not make it into the kit. Above is how you repair if you want ahead of re-release.

**Comment by mpinuel** [comment]
Hi @JeneferM-MSFT 

I made the changes in the PVA Flow to try to fix the issue in the v1.71.1, but I run the process again and we still have the error:

- I applied the following changes in the "See if Modified" Scope:
![image](https://user-images.githubusercontent.com/32450895/100063432-8126a200-2e31-11eb-90e7-ede1952941eb.png)

- I got the same error in the "Get_this_Bot_from_CoE" action: **admin_pva With Id = XXXX Does Not Exist**

- And this is the failed run of the flow, with the changes already made:
![image](https://user-images.githubusercontent.com/32450895/100063925-26da1100-2e32-11eb-80bb-6f3beea66929.png)

Should we make any other modifications to the Flow?

Thanks!

**Comment by albertocaa1317** [comment]
Hi @mpinuel,
review this step in your flow, it's different that the workaround propose by Jenefer:

![image](https://user-images.githubusercontent.com/57954993/100067087-1deb3e80-2e36-11eb-90f0-9ee39d231555.png)

By the other hand, this issue in my case was fixed on the new version 1.71.5

**Comment by mpinuel** [comment]
Thanks @albertocaa1317 ! That was the error!

I changed the variable **varBotNeedsUpdated** that I had for the variable **varBotIsNew** that Jenefer had in her workaround and it works correctly!

Thank you both!

Regards,
Miguel

**Comment by JeneferM-MSFT** [comment]
Alberto, the mystery continues! We are investigating how it got lost.

**Comment by albertocaa1317** [comment]
@JeneferM-MSFT can be that your last comment is about this other issue? 
[https://github.com/microsoft/powerapps-tools/issues/581](https://github.com/microsoft/powerapps-tools/issues/581)

**Comment by manuelap-msft** [comment]
Updated with the new release that just went out. Thank you!
